# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
getPrize = ->
  prize = 0
  if $('.cant').length > 0
    $('.cant').each ->
      prize += (if parseFloat($(this).val()) < 0 then 0 else parseFloat($(this).val())) * $(this).data('prize')
      return
  $('.containerprize').text 'Total: ' + prize + '€'
  return

$(document).ready ->
  console.log 'HOLAAAA'
  $('.titlepedido').hide()
  $('.tipos').on 'click', ->
    $('.tipos').removeClass 'selected'
    $(this).addClass 'selected'
    $('.card-food').show()
    $('.card-food').removeClass 'disabled'
    if $(this).text() != 'Todos'
      $('.card-food:not(.' + $(this).html() + ')').hide()
      $('.card-food:not(.' + $(this).html() + ')').addClass 'disabled'
    else
      $('.tipos').removeClass 'selected'
    return
  $('.alerg').on 'click', ->
    $('.alerg').removeClass 'selected'
    $(this).addClass 'selected'
    $('.card-food:not(.disabled)').fadeTo 'slow', 1
    if $(this).text() != 'Limpiar'
      $('.hasalerg_' + $(this).html().replace(' ', '-') + ':not(.disabled)').fadeTo 'slow', 0.33
    else
      $('.alerg').removeClass 'selected'
    return
  $('.anadirpedido').on 'click', ->
    console.log 'tb llega'
    $('.titlepedido').fadeIn()
    $('.containerpedido').append '<div class="row"><div class="col-xs-offset-1 col-xs-1"><a><i class="fa fa-times quitar"></i></a>&nbsp;</div><div class="col-xs-4">' + $(this).parent().find('.titles').html() + '</div><div class="col-xs-5"><input type="number" value="1" class="cant" data-prize="' + parseFloat($(this).parent().find('.prize').text().replace('€', '')) + '"></div></div>'
    getPrize()
    $('.cant').on 'keyup change click', ->
      getPrize()
      return
    $('.containerpedido .fa-times').on 'click', ->
      $(this).parent().parent().parent().remove()
      if $('.containerpedido').children().length == 0
        $('.titlepedido').fadeOut()
      getPrize()
      return
    return
  return

# ---
# generated by js2coffee 2.2.0